Repository open-template-hub/company-profile-ui-template, pull requests merged in 2021-09, with the labels that each got.

#22 Version Update PR
  package.json
Labels: workflow

#24 Version Update PR
  package.json
Labels: workflow

#33 Version Update PR
  package.json
Labels: workflow

#35 Version Update PR
  package.json
Labels: workflow

#37 workflow: Version Update PR
  package.json
Labels: workflow

#28 bug: General Bug Fix
  src/app/component/common/card/card1/card1.component.scss
  src/app/component/common/card/testimonial-card/testimonial-card.component.html
  src/app/component/common/card/testimonial-card/testimonial-card.component.scss
  src/app/component/common/swiper-wrapper/swiper-wrapper.component.html
  src/app/component/common/swiper-wrapper/swiper-wrapper.component.scss
  src/app/component/common/swiper-wrapper/swiper-wrapper.component.ts
  src/app/component/nav/common/bottom-nav/bottom-nav.component.html
  src/app/component/nav/common/bottom-nav/bottom-nav.component.scss
  src/app/component/nav/landing/landing-layout-top-nav/landing-layout-top-nav.component.scss
  src/app/page/raw-landing-layout/home/home.component.html
Labels: bug

#47 bug: test reset demo on pr open
  README.md
Labels: bug

#49 Bug/issue 48 test flow
  FAVICON_GENERATION.md
  README.md
Labels: bug

#52 Bug/test flow
  FAVICON_GENERATION.md
  README.md
Labels: bug

#54 Feature/flow example ticket
  .github/workflows/on-version-update.yml
Labels: feature

#64 Workflow/version update
  package.json
Labels: workflow

#71 Workflow/version update
  package.json
Labels: workflow

#73 Workflow/version update
  package.json
Labels: workflow

#79 Workflow/version update
  package.json
Labels: workflow

#81 Workflow/version update
  package.json
Labels: workflow

#83 Workflow/version update
  package.json
Labels: workflow

#90 Workflow/version update
  package.json
Labels: workflow

#105 Feature/contact us page
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/component/common/button/button1/button1.component.html
  src/app/component/common/button/button1/button1.component.scss
  src/app/component/common/button/button1/button1.component.ts
  src/app/component/nav/common/bottom-nav/bottom-nav.component.html
  src/app/component/nav/landing/landing-layout-top-nav/landing-layout-top-nav.component.html
  src/app/data/constant.ts
  src/app/data/contact-us/contactUsData.ts
  src/app/data/countries.ts
  src/app/page/landing-layout/contact-us/contact-us.component.html
  src/app/page/landing-layout/contact-us/contact-us.component.scss
  src/app/page/landing-layout/contact-us/contact-us.component.spec.ts
  src/app/page/landing-layout/contact-us/contact-us.component.ts
  src/environments/environment-common.ts
  src/environments/version.ts
  src/index.html
  src/styles/alert/alert.scss
  src/styles/input/input.scss
Labels: feature

#119 Workflow/version update
  package.json
Labels: workflow

#121 Workflow/version update
  package.json
Labels: workflow

#124 Workflow/version update
  package.json
Labels: workflow

#126 Workflow/version update
  package.json
Labels: workflow

#130 Workflow/version update
  package.json
Labels: workflow

#139 Workflow/version update
  package.json
Labels: workflow

#141 Workflow/version update
  package.json
Labels: workflow

#143 Workflow/version update
  package.json
Labels: workflow

#147 Workflow/version update
  package.json
Labels: workflow

#157 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#159 Workflow/version update
  package.json
Labels: workflow

#161 Workflow/version update
  package.json
Labels: workflow

#172 Workflow/dependency update
  package.json
Labels: workflow

#174 Workflow/version update
  package.json
Labels: workflow

#176 Workflow/version update
  package.json
Labels: workflow

#178 Workflow/version update
  package.json
Labels: workflow
